### ISSUE TITLE
Weird pink stripe to the right side of AVIF generated from PNG

### ISSUE THREAD

**Issue by pdobrescu** [kornelski/cavif-rs#70] opened 2023-03-22 19:07 UTC
hello and thanks for this great converter! 

I'm having some weird issues with certain PNG files that get a pink line to the right side, but only on some specific (old) mobiles. I tested on 2 Huawei devices, using Chrome (I don't have the exact version at hand right now) and the images look like this:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/1044106/227010136-5830b288-419a-4428-8536-585da2959975.png">

The source PNG is this one:

![image](https://user-images.githubusercontent.com/1044106/227010606-1bff6236-ff49-43a4-97f4-97a00b6befbd.png)

And the resulting AVIF is this one (it looks like I can't upload AVIFs to GH):

[Test_AVIF.avif.zip](https://github.com/kornelski/cavif-rs/files/11043826/Test_AVIF.avif.zip)

Do you have any ideas why that pink line shows up? Any help will be much appreciated!

**Comment by kornelski** [comment] 2023-03-22 20:42
This is bug in Microsoft's decoder. Duplicate of #60

**Comment by kornelski** [comment] 2023-03-23 02:05
The image you've attached displays fine for me in Firefox, Safari, and Chrome. 

This looks like a problem reported previously, about a bug in Microsoft's AVIF decoder in Windows: #60

**Comment by pdobrescu** [comment] 2023-03-23 13:25
hello @kornelski and thanks for the quick reply. While I can understand this issue is similar to the one you mentioned, I have encountered it on 2 different Android devices. Is it possible that these older Android phones are using Microsoft's AVIF decoder? On newer Android devices the issue cannot be replicated indeed.

**Comment by kornelski** [comment] 2023-05-06 13:55
I've made a new release with latest rav1e encoder, which may or may not help. 

I still suspect that it's the same bug in the decoders, and possibly Windows and old Android used the same library.

**Closed by kornelski** 2023-05-06 13:55 UTC
